using System;
using System.IO;
using System.Text;

namespace Qorpent.Scaffolding{
	/// <summary>
	/// 
	/// </summary>
	public class Production{
		/// <summary>
		/// Метка автогенерации
		/// </summary>
		public const string AUTOGENERATED_MASK = "QPT:::AUTOGENERATED";
		/// <summary>
		/// Имя файла
		/// </summary>
		public string FileName { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public bool CanBeSaved{
			get{
				if (null == GetContent) return false;
				if (!OnlyIfAutogenrate) return true;
				if (!File.Exists(FileName)) return true;
				var buff = new char[100];
				using (var f = File.OpenRead(FileName)){
					using (var sr = new StreamReader(f)){
						sr.Read(buff, 0, buff.Length);
					}
				}
				return new string(buff).Contains(AUTOGENERATED_MASK);
			}
		}

		/// <summary>
		/// Содержимое
		/// </summary>
		public Func<string> GetContent;
		/// <summary>
		/// Проверять наличие файла и наличие в нем специальной последовательности QPT:::AUTOGENERATED
		/// </summary>
		public bool OnlyIfAutogenrate { get; set; }
	}
}