
define([
    "the-root",
    "the-object",
    "the-interpolation",
    "the-jsonify",
    "the-http",
    "the-expression",
    "the-collections-core",
    "the-collections-layered",
    "the-collections-linked",
    "the-collections-history",
    "the-collections-linq",
    "the-action",
    "the-login",
    'the-angular-unsafe',
    'the-angular-autocomplete',
    'the-angular-autoselect',
    'the-angular-ellipse',
    'the-angular-datetimepicker',
    'the-uploader',
    'the-angular-dialog',
    'the-angular-controlgroup',
    'the-angular-viewcontext',
    'the-angular-onenter',
    'the-design-stackedbutton',
    'the-wiki',
    'the-menu',
    'the-settings',
    'the-errorcatcher',
    'the-refresh',
    'autocomplete-html',
    'the-domutils',
    'the-dropdown',
    'the-uistate',
    'the-tools',
    'the-print',
    'the-dates',
    'the-report',
    'the-hash',
    'the-log'
], function ($the) {
    return $the;
});
//# sourceMappingURL=the.js.map