using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Qorpent.BSharp;
using Qorpent.Utils.Extensions;

namespace Qorpent.Scaffolding.Orm{
	/// <summary>
	/// Формирует вспомогательный класс адаптера для DataReader
	/// </summary>
	public class GenerateExtendedCachedModel: CodeGeneratorTaskBase
	{
		private StringBuilder o;
		private IBSharpClass[] _tables;

		/// <summary>
		/// 
		/// </summary>
		public GenerateExtendedCachedModel()
			: base()
		{
			ClassSearchCriteria = "dbtable";
			DefaultOutputName = "Orm";
		}

		/// <summary>
		/// 
		/// </summary>
		private const string Header = "/*" + Production.AUTOGENERATED_MASK + "*/\r\n" + @"
//////////////////////////////////////////////////////////////////////
////       AUTO-GENERATED WITH  GenerateExtendedCachedModel     ////
//////////////////////////////////////////////////////////////////////
";
		/// <summary>
		/// 
		/// </summary>
		/// <param name="targetclasses"></param>
		/// <returns></returns>
		protected override IEnumerable<Production> InternalGenerate(IBSharpClass[] targetclasses){

			var genfactory = new Production{
				FileName = "Adapters/Model_Caches.cs",
				GetContent = ()=>GenerateModelClass()
			};
			yield return genfactory;
		}

		private string GenerateModelClass(){
			o = new StringBuilder();
			_tables = _context.ResolveAll("dbtable").OrderBy(_ => _.Name).ToArray();
			var ns = _tables.Select(_ => _.Namespace).GroupBy(_ => _).OrderByDescending(_ => _.Count()).First().Key;
			o.AppendLine(Header);
			o.AppendLine("using System;");
			o.AppendLine("using Qorpent.Data;");
			o.AppendLine("using Qorpent.Log;");
			o.AppendLine("using Qorpent.IoC;");
			o.AppendLine("using Qorpent.Data.Connections;");
			o.AppendLine("using Qorpent.Data.DataCache;");
			o.AppendLine("using System.Linq;");
			o.AppendLine("using System.Collections.Generic;");
			o.AppendFormat("namespace {0}.Adapters {{\r\n", ns);
			o.AppendLine("\t///<summary>Model for " + ns + " definition</summary>");
			o.AppendLine("\tpublic partial class Model {");
			GenerateSupportProperties();
			GenerateCacheInstances(ns);
			GenerateSetupLinksMethod(ns);
			o.AppendLine("\t}");
			o.AppendLine("}");
			return o.ToString();
		}

		private void GenerateSetupLinksMethod(string ns){
			o.AppendLine("\t\t///<summary>Setup auto load behavior for linked classes</summary>");
			o.AppendLine("\t\tprotected void SetupLoadBehavior<T>(ObjectDataCache<T> cache)where T:class,new(){");
			o.AppendLine("\t\t\tswitch(typeof(T).Name){");
			IList<Tuple<IBSharpClass,XElement[],Tuple<IBSharpClass,XElement>[]>> dataToGenerate = new List<Tuple<IBSharpClass, XElement[], Tuple<IBSharpClass, XElement>[]>>();
			foreach (var t in _tables){
				var ownrefs = t.Compiled.Elements("ref").ToArray();
				var incomes = OrmGenerationExtensions.FindIncomeRefes(_context, t,true).ToArray();
				if (0 == ownrefs.Length && 0 == incomes.Length) continue;
				o.AppendLine("\t\t\t\tcase \"" + t.Name + "\" : Setup" + t.Name + "LoadBehavior(cache as ObjectDataCache<"+t.Name+">);break;");
				dataToGenerate.Add(new Tuple<IBSharpClass, XElement[], Tuple<IBSharpClass, XElement>[]>(t,ownrefs,incomes));
			}
			o.AppendLine("\t\t\t\tdefault: break;");
			o.AppendLine("\t\t\t}");
			o.AppendLine("\t\t}");

			foreach (var setupinfo in dataToGenerate){
				var t = setupinfo.Item1;
				o.AppendLine("\t\t///<summary></summary>");
				o.AppendLine("\t\tprotected void Setup" + t.Name + "LoadBehavior(ObjectDataCache<"+t.Name+"> cache){");
				o.AppendLine("\t\t\tcache.OnAfterUpdateCache+= (s,ids,c,ctx) => {");
				o.AppendLine("\t\t\t\tvar mycache = s as ObjectDataCache<"+t.Name+">;");
				o.AppendLine("\t\t\t\tvar targets = ids.Select(_=>mycache.Get(_,c)).ToArray();");
				o.AppendLine("\t\t\t\tforeach(var t in targets){");
				o.AppendLine("\t\t\t\t\tif(t.Id == -9999||t.Id==0)continue;");
				foreach (var element in setupinfo.Item2){
					GenerateSetupOwnRef(t, element);
				}
				o.AppendLine("\t\t\t\t}");
				if (setupinfo.Item3.Length != 0)
				{
					o.AppendLine("\t\t\t\tif (ids.Count > 0 && !(ids.Count == 1 && (ids[0] == 0 || ids[0]==-9999))){");
					o.AppendLine("\t\t\t\t\tvar inids = string.Join(\",\",ids.Where(_=>_!=0 && _!=-9999));");
					foreach (var source in setupinfo.Item3.OrderBy(_=>_.Item1.Name).ToArray()){
						var colt = source.Item1;
						var revref = source.Item2;
						GenerateSetupCollection(t, colt, revref);
					}
					o.AppendLine("\t\t\t\t}");
				}
				o.AppendLine("\t\t\t};");
				o.AppendLine("\t\t}");
			}
		}

		private void GenerateSetupCollection(IBSharpClass t, IBSharpClass colt, XElement revref){
			var code = revref.Attr("code");
	
			var mname = colt.Name;
			if (mname.EndsWith("s")){
				mname += "es";
			}
			else{
				mname += "s";
			}
			if (code == "Parent")
			{
				mname = "Children";
			}
			
			if (code != t.Name && code!="Parent")
			{
				
				mname += "By" + code;
				
			}
			var propname = t.Name + mname;
			
			var alprop = "AutoLoad" + propname;

			o.AppendLine("\t\t\t\t\tif(" + alprop + "){");
			o.AppendLine("\t\t\t\t\t\tvar q = string.Format(\"(" + code + " in ({0}))\",inids);");
			var cache = colt.Name;
			if (code == "Parent"){
				cache = "cache";
			}
			o.AppendLine("\t\t\t\t\t\tvar nestIds = " + cache + ".UpdateSingleQuery(q, ctx,c, null, true);");
			o.AppendLine("\t\t\t\t\t\tforeach(var nid in nestIds){");
			o.AppendLine("\t\t\t\t\t\t\tvar n=" + cache + ".Get(nid);");
			o.AppendLine("\t\t\t\t\t\t\tvar t=cache.Get(n."+code+"Id);");
			o.AppendLine("\t\t\t\t\t\t\tt."+mname+".Add(n);");
			o.AppendLine("\t\t\t\t\t\t}");
			o.AppendLine("\t\t\t\t\t}");

		}

		private void GenerateSetupOwnRef(IBSharpClass t, XElement e){
			var code = e.Attr("code");
			var cls = e.Attr("to");
			var fld = "Id";
			if (string.IsNullOrWhiteSpace(cls)){
				cls = e.Attr("code");
			}
			else{
				var parts = cls.Split('.');
				cls = parts[parts.Length - 2];
				fld = parts[parts.Length - 1];
			}
			o.AppendLine("\t\t\t\t\tif(AutoLoad" + t.Name + code + " && null==t." + code +(fld=="Id"? (" && -9999 != t."+code+fld):"")+   "){");
			o.AppendLine("\t\t\t\t\t\tt." + code + "=" + cls + ".Get(t." + code + fld + ",c);");
			o.AppendLine("\t\t\t\t\t}");
		}

		private void GenerateSupportProperties(){
			o.AppendLine(@"
		private IUserLog _log;
		private IDatabaseConnectionProvider _connectionProvider;
		private IUserLog _sqlLog;
		///<summary>initiator for caches</summary>
		protected ObjectDataCache<T> InitCache<T>()where T:class,new(){
			var result = new ObjectDataCache<T>{ Adapter = GetAdapter<T>(), ConnectionProvider  = ConnectionProvider, Log= Log, SqlLog= SqlLog, ConnectionString = ConnectionString };
			SetupLoadBehavior(result);
			return result;
		}
		///<summary>
		///Sql connection descriptor
		///</summary>
		public string ConnectionString{get;set;}
		/// <summary>
		/// Служба генерации соединений
		/// </summary>
		[Inject]
		protected  IDatabaseConnectionProvider ConnectionProvider{
			get { return _connectionProvider??(_connectionProvider =new DatabaseConnectionProvider{IgnoreDefaultApplication = true}); }
			set { _connectionProvider = value; }
		}
		/// <summary>
		/// Журнал общих событий
		/// </summary>
		public IUserLog Log{
			get { return _log ?? (_log= StubUserLog.Default); }
			set { _log = value; }
		}

		/// <summary>
		/// Журнал событий SQL
		/// </summary>
		public IUserLog SqlLog{
			get { return _sqlLog ?? (_sqlLog=StubUserLog.Default); }
			set{
				_sqlLog = value;
			}
		}");
		}

		private void GenerateCacheInstances(string ns){
			foreach (var table in _tables){
				var n = table.Name;
				if (ns != table.Namespace){
					n = table.Namespace + "." + n;
				}
				o.AppendLine("\t\tprivate ObjectDataCache<" + n + "> _" + table.Name + "Cache;");
				o.AppendLine("\t\t///<summary>Cache of " + table.Name + "</summary>");
				o.AppendLine(
					string.Format(
						"\t\tpublic ObjectDataCache<{0}> {1} {{get {{ return _{1}Cache ?? (_{1}Cache = InitCache<{0}>());}}}}", n,
						table.Name));
			}
		}
	}
}