#!/bin/sh
root=../..
mkdir
for d in ${root}/Leaflet* ; do
    src=${d}/dist
    echo "copying ${src}"
    mkdir ./src/js/tmp-import/
    mkdir ./src/css/tmp-import/
    cp ${src}/*.js ./src/js/tmp-import/
    cp ${src}/*.css ./src/css/tmp-import/
    cp -rf ${src}/images/*.png ./dist/css/images
done