/*QPT:::AUTOGENERATED*/define(['bxlui_api','bxlui_types','angular', 'bxldev_ext','settings'], function (Api, Types) {
    angular.module('bxlui_controllers',[, 'bxldev_ext','settings'])
        .controller('bxlui_BxlDev', ['$scope','$http','$rootScope', 'bxldev_ext','settings', function ($scope, $http, $rootScope, bxldev_ext,settings) { 
                $scope.api = Api($http, $rootScope);
                $scope.view = 'BxlDev.html';
				$scope.title= 'BxlDev';
				settings($scope,{before:true,type:"settings"});
				$scope.bxoptions = new Types.BxOptions($.extend({},$scope.settings.get('bxlui-bxoptions')));
				$scope.$watch('bxoptions',function(n,o){$scope.settings.set('bxlui-bxoptions',n)},true);
				$scope.bxquery = new Types.ToXmlQuery($.extend({},$scope.settings.get('bxlui-bxquery')));
				$scope.$watch('bxquery',function(n,o){$scope.settings.set('bxlui-bxquery',n)},true);
				bxldev_ext($scope,{code:"bxldev_ext"});

		}])
;
});