//QPT:::AUTOGENERATED
// Type definitions for bxlui

define (["bxlui_types","actionBuilder"], function(types,actionBuilder) {
	return  function  ($http, siteroot) {
		var __ToXml = null;
		var __result = {};

		Object.defineProperty(__result,'ToXml',{get : function(){  return __ToXml||(__ToXml = actionBuilder($http,siteroot,{
			code : "ToXml",
			name : "Запрос на публикацию",
			arguments : types.ToXmlQuery,
			url : "/toxml",
			method : "QPOST",
			postfield : "Script",
			parameters : null
		}))},writeable:false});

		return __result;
	}
});
